
package com.kenneth.taskforge.export;

import com.kenneth.taskforge.model.Plan;
import com.kenneth.taskforge.model.Task;
import com.kenneth.taskforge.store.Store;

import java.io.File;
import java.io.OutputStreamWriter;
import java.io.FileOutputStream;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class MarkdownExport {
    public static File export(Plan plan) throws Exception {
        LocalDate week = plan.getWeekStart()==null? LocalDate.now() : plan.getWeekStart();
        String name = "Weekly_Plan_" + week.format(DateTimeFormatter.ISO_DATE) + ".md";
        File out = Store.plansDir().resolve(name).toFile();

        StringBuilder sb = new StringBuilder();
        sb.append("# Weekly Plan — ").append(week.format(DateTimeFormatter.ISO_DATE)).append("\n\n");
        sb.append("> Generated by TaskForge (Swing)\n\n");

        sb.append("## Tasks\n\n");
        sb.append("| # | Title | Priority | Due | Est. Hours | Tags |\n");
        sb.append("|---|-------|----------|-----|------------|------|\n");
        int i=1;
        for(Task t: plan.getTasks()){
            sb.append("| ").append(i++).append(" | ")
              .append(esc(t.getTitle())).append(" | ")
              .append(prio(t.getPriority())).append(" | ")
              .append(t.dueString()).append(" | ")
              .append(t.getHours()==null? "" : t.getHours()).append(" | ")
              .append(esc(t.getTags())).append(" |\n");
        }
        sb.append("\n---\n");
        sb.append("_Hint_: Use File → Export Markdown again anytime.\n");

        try(Writer w = new OutputStreamWriter(new FileOutputStream(out), StandardCharsets.UTF_8)){
            w.write(sb.toString());
        }
        return out;
    }

    private static String esc(String s){ return s==null? "" : s.replace("|", "\\|"); }
    private static String prio(int p){ return p==1? "High" : p==2? "Medium" : "Low"; }
}
